name: Deploy Repository A

on: push
jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Remove .github folder
      shell: pwsh
      run: |
        Remove-Item -Path ".github\*.yml" -Recurse -Force
        Remove-Item -Path ".git" -Recurse -Force 
    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "D:\Path*" -Recurse -Force

    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "D:\Path" -Force      
