name: Publish to GitHub Package Registry

on: [workflow_dispatch]

env:
  version-major: 1
  version-minor: 1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Publish Package
      uses: actions/upload-artifact@v2
      with:
        name: '${{ env.version-major }}.${{ env.version-minor }}.${{github.run_number}}'
        path: .

    - name: Print Artifact ID
      run: |
          ARTIFACT_ID=$(curl -s -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
            | jq -r '.artifacts[0].id')
          echo "Artifact ID: $ARTIFACT_ID"  
  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
    - name: downlaod the packages
      uses: actions/download-artifact@v3
      with: 
        name: '${{ env.version-major }}.${{ env.version-minor }}.${{github.run_number}}'
        
    - name: Display structure of downloaded files
      shell: pwsh
      run: |
        dir

    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "C:\test\*" -Recurse -Force
    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "C:\test" -Force       

  

  

        
