name: Publish to GitHub Package Registry

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    
      
    - name: Publish Package
      uses: actions/upload-artifact@v2
      with:
        name: my-package
        path: ./my-package
