name: Deploy Repository A

on: push
jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: master

    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "D:\Path*" -Recurse -Force
    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "D:\Path" -Force

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ashokeruvaram/nodejsapplication
        path: master

    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "D:\Path1*" -Recurse -Force
    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "D:\Path1" -Force

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ashokeruvaram/gs-spring-boot
        path: master

    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "D:\Path2*" -Recurse -Force
    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "D:\Path2" -Force        
    # Continue with other steps as needed
