name: Publish to GitHub Package Registry

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Publish Package
      uses: actions/upload-artifact@v2
      with:
        name: my-package
        path: .

  

  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
    - name: downlaod the packages
      uses: actions/download-artifact@v3
      with: 
        name: my-package
        
    - name: Display structure of downloaded files
      shell: pwsh
      run: |
        Get-ChildItem -Recurse 
        
