name: Prodrollback

on: [workflow_dispatch]

env:
  pacakge-version: 1.1.75
jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: downlaod the packages
      uses: aochmann/actions-download-artifact@1.0.0
      with:
        github_token: ${{secrets.GITHUB_TOKEN}} 
        repo: ${{github.repository}}
        name: 1.1.75
        path: .
        
    - name: Display structure of downloaded files
      shell: pwsh
      run: |
        dir

    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "C:\test\*" -Recurse -Force
    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "C:\test" -Force  
