name: Prod

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download the packages
        shell: bash
        run: |
          owner="ashokdevopsorg"
          repo="node-js-sample"
          runId="8323049963"
          token="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"

          url="https://api.github.com/repos/$owner/$repo/actions/runs/$runId/artifacts"

          response=$(curl -X GET -s -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" "$url")
          ArtifactId=$(echo "$response" | jq -r .artifacts[0].id)
          Write-Host "ArtifactId"
          # Download the artifact zip file
          curl -L \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $token" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -o artifact.zip \
            "https://api.github.com/repos/$owner/$repo/actions/artifacts/$ArtifactId/zip"

      - name: Display structure of downloaded files
        shell: bash
        run: |
          ls -ltr
         # unzip -v artifact.zip
