name: Prod

on: [workflow_dispatch]

env:
  pacakge-version: 1.1.75
jobs:
  
  deploy:
    runs-on: windows-latest
    steps:
    - name: downlaod the packages
      shell: pwsh
      run: |
        $accessToken = "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"
        $owner = "ashokdevopsorg"
        $repo = "node-js-sample"
        $runId = "8389493864"
        $url = "https://api.github.com/repos/$owner/$repo/actions/runs/$runId/artifacts"
        $response = Invoke-RestMethod -Uri $url -Headers @{
            "Authorization" = "Bearer $accessToken"
            "Accept" = "application/vnd.github.v3+json"
        }

        $ArtifactId = $response.artifacts.id

        $Headers = @{
            "Authorization" = "token $accessToken"
            "Accept" = "application/vnd.github.v3+json"
        }

        $ArtifactUrl = "https://api.github.com/repos/$owner/$repo/actions/artifacts/$ArtifactId/zip"
        Invoke-RestMethod -Uri $ArtifactUrl -Headers $Headers -OutFile artifact.zip
                      
   
    - name: Display structure of downloaded files
      shell: pwsh
      run: |
        dir 
