name: Prodrollback

on: [workflow_dispatch]

env:
  pacakge-version: 1.1.75
jobs:
  
  deploy:
    runs-on: self-hosted
    steps:
    - name: downlaod the packages
      uses:  benday-inc/download-artifact@main
      with:
        token: ${{ secrets.TOKEN_WITH_PERMISSIONS }} 
        repository_owner: 'ashokdevopsorg'
        repository_name: 'node-js-sample'
        workflow_name: 'Publish to GitHub Package Registry'
        #branch_name: 'master'
        artifact_name: '1.1.75'
        run_id: 8344693852
        download_path: .
        download_filename: 1.1.75.zip
        
    - name: Display structure of downloaded files
      shell: pwsh
      run: |
        dir

    - name: Remove Existing Files from Destination Folder
      shell: pwsh
      run: |
        Remove-Item -Path "C:\test\*" -Recurse -Force
    - name: Move Code to Destination Folder
      shell: pwsh
      run: |
        
        # Move all folders and files to the destination folder
        Move-Item -Path * -Destination "C:\test" -Force  
