name: Prod

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download the packages
      shell: bash
      run: |
        owner="ashokdevopsorg"
        repo="node-js-sample"
        runId="8323049963"
        token="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"

        url="https://api.github.com/repos/$owner/$repo/actions/runs/$runId/artifacts"
       
        response=$(curl -X GET -s -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" "$url")
        ArtifactId=$(echo "$response" | jq -r .artifacts[0].id)

        ArtifactUrl="https://api.github.com/repos/$owner/$repo/actions/artifacts/$ArtifactId/zip"
        curl -s -H "Authorization: Bearer $token" -H "Accept: application/vnd.github.v3+json" "$ArtifactUrl" -o artifact.zip
   
    - name: Display structure of downloaded files
      shell: bash
      run: |
        ls -ltr
