name: Auto Pull Latest Code

on: workflow_dispatch
  
jobs:
  pull_latest_code:
    runs-on: self-hosted  # Specify the label of your self-hosted runner

    steps:
    - name: executing git clone
      run: |
        cd "C:\src
        git clone https://github.com/ashokdevopsorg/node-js-sample.git
